---
- hosts: webservers
  become: yes
  tasks:
    - name : installing httpd
      yum:
        name: "*"
        state: latest
    - name: restart httpd
      service:
        name: httpd
        state: restarted
  handlers:
    - name: Restart-httpd
      service:
        name: httpd
        state: restart

