---
 - hosts: all
   become: yes
   tasks:
    - name: installing httpd
      yum:
       name: httpd
       state: present
    - name: start httpd service
      service:
       name: httpd
       state: started

